n_ens = 1

# Space

dx = 10000
dy = 10000

# Layers
H = [400, 1100]
g_prime = [9.81, 0.025]

# Water density
rho0 = 1000.0

# Drag
bottom_drag_coef = 3.60577e-8

# Time discretization
dt = 7200

# Output
folder = "enatl60_surfml_winter"
prefix = "results_optim"

# Simulation
duration = 240 # Number of steps

# Optimization
optimization_steps = 25
cycles = 4
separation = 0
## Regularization
gamma = 0.1

# Season
season = "winter"